//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_CP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingHistory
    {
        public int parking_id { get; set; }
        public int drone_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.TimeSpan> time_from { get; set; }
        public Nullable<System.TimeSpan> time_to { get; set; }
        public float total_cost { get; set; }
    
        public virtual Drone Drone { get; set; }
        public virtual ParkingPlace ParkingPlace { get; set; }
    }
}
