//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using DataAccess_CP.Entities;

namespace DataAccess_CP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseProjectDBEntities : DbContext
    {
        public CourseProjectDBEntities()
            : base("name=CourseProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditCard> CreditCard { get; set; }
        public virtual DbSet<Drone> Drone { get; set; }
        public virtual DbSet<ParkingPlace> ParkingPlace { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ParkingHistory> ParkingHistory { get; set; }
        public virtual DbSet<ParkingPayment> ParkingPayment { get; set; }
        public virtual DbSet<UserInRole> UserInRole { get; set; }
        public virtual DbSet<UsersCard> UsersCard { get; set; }
    }
}
