//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess_CP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingPayment
    {
        public int parking_id { get; set; }
        public string payment_per_time_unit { get; set; }
        public int time_unit { get; set; }
        public int currency { get; set; }
    
        public virtual ParkingPlace ParkingPlace { get; set; }
    }
}
